### ISSUE TITLE
image to ascii python code

### ISSUE THREAD

**Issue by Mayank9404** [Mayank94043626/python-projects-open-source#2]
# Description
This Python Project will take a simple image and print out an ASCII-art.

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Mayank94043626** [comment]
Completed
