### ISSUE TITLE
Password Validator

### ISSUE THREAD

**Issue by srshobhit72** [Mayank94043626/python-projects-open-source#40]
# Description

Python program to check if the password contains the following:;
    1. length between 8 and 16.
    2.uppercase letter.
    3.lowercase letter.
    4.characters like [@,#,$,&].
    5. digits.

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by srshobhit72** [comment]
I would like to work on it.

**Comment by Mayank94043626** [comment]
Assigned to you @srshobhit72

**Comment by srshobhit72** [comment]
ok will let you know soon.
