### ISSUE TITLE
Average Calculator in Python

### ISSUE THREAD

**Issue by ak-404** [Mayank94043626/python-projects-open-source#49]
# Description

Sir, I make a average calculator in python. It takes user input until user enters "done" & then it print the count of entered no. , their total & the average. pls add it to the repo.
## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by anonymous-sidhax** [comment]
Please assign this to me, I want to try it.
